logging:
  level: INFO
  loggers:
    br.mack.aluno: DEBUG

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost:3308
  validationQuery: "SELECT 1"
